language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121

script:
  - dotnet restore WonderwareOnlineSDK
  - dotnet restore WonderwareOnlineSDK.UnitTests
  - dotnet build WonderwareOnlineSDK -c Release
  - dotnet build WonderwareOnlineSDK.UnitTests -c Release
  - dotnet test ./WonderwareOnlineSDK.UnitTests/bin/BWS/Release/netcoreapp1.1/WonderwareOnlineSDK.UnitTests.dll