language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
install:
  - nuget restore WonderwareOnlineSDK.sln
  - nuget install xunit.runnner.console -Version 2.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./WonderwareOnlineSDK.csproj
  - dotnet restore WonderwareOnlineSDK.UnitTests
  - dotnet build WonderwareOnlineSDK.UnitTests -c Release
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./WonderwareOnlineSDK.UnitTests/bin/Release/WonderwareOnlineSDK.UnitTests.dll