language: csharp
solution: WonderwareOnlineSDK.sln
install:
  - nuget restore WonderwareOnlineSDK.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release WonderwareOnlineSDK.csproj
  - dotnet restore WonderwareOnlineSDK.UnitTests
  - dotnet build WonderwareOnlineSDK.UnitTests -c Release
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./WonderwareOnlineSDK.UnitTests/bin/Release/WonderwareOnlineSDK.UnitTests.dll