language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.1

script:
  - dotnet restore WonderwareOnlineSDK
  - dotnet restore WonderwareOnlineSDK.UnitTests
  - dotnet build WonderwareOnlineSDK -c Release
  - dotnet build WonderwareOnlineSDK.UnitTests -c Release
  - dotnet test WonderwareOnlineSDK.UnitTests/WonderwareOnlineSDK.UnitTests.csproj